sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
addons:
  apt:
    packages:
    - graphviz
install: pip install Markdown docutils textile Sphinx
script: python -m unittest discover -s tests -v
