sudo: false
language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      sudo: required
      dist: xenial
    - python: "pypy"
    - python: "pypy3"
install: pip install Markdown pymdown-extensions docutils textile pygments codecov
script: coverage run setup.py test
after_success: codecov
